name: Python application

on: [push]

jobs:
  start:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: run
      run: |
        pip install -r requirement.txt
        python main.py
